### ISSUE TITLE
Can't update previously installed libraries

### ISSUE THREAD

**Issue by FuzzyWuzzie** [underscorediscovery/snowfall#6]
Have flow, snow, luxe installed.

Ran:

```bash
haxelib install snowfall
haxelib run snowfall update snow
```

Got:

```
snowfall 0.0.13


> haxe - version - 3.2.1
> haxelib - path - C:/HaxeToolkit/haxe/lib

Called from ? line 1
Called from M.hx line 11
Called from M.hx line 27
Called from M.hx line 65
Called from M.hx line 35
Called from util/Haxe.hx line 41
Uncaught exception - Invalid field access : major
```

Tried removing snow, luxe, etc and going from a clean slate; got the same issue. Running haxelib `3.2.0-rc.3`, haxe `3.2.1` on Windows 8.1 x64.

**Comment by underscorediscovery** [comment]
It comes from this line, 

`check_lib_update('hxcpp');`

Which I'm guessing relates to hxcpp not being installed or configured for git, I have #1 where I'll ensure hxcpp testing isn't causing crashes like this.

**Comment by FuzzyWuzzie** [comment]
Yup, definitely needed hxcpp installed. Is there a reason snowfall doesn't pull that as well?

**Comment by underscorediscovery** [comment]
:100:
